apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-plugins
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/plugins"